#
# Basic yaml code to get the ESP32-2432S028 working in Home Assistant as a 12-button "Stream Deck"
# ============================================================
# Author: Aaron Stewart @makeitworktech, with the help of ChatGPT.
# GitHub: https://github.com/makeitworktech
#
# modified 20 Aug 2025 Larry Goodale @TTechGuy to make the button presses work correctly
# adding in missing code from other yaml files and adding in substitutions for fonts, etc 
#
# ============================================================ 
# NOTE:
# In order for this to work you need to add the following settings in your secrets.yaml file:
# - api_key
# - ota_password
# - wifi_ssid
# - wifi_password
# - ap_password
#
# Create a folder named fonts in your ESPHome folder, and copy the 
# files fonts/Arimo-Regular.ttf and fonts/materialdesignicons-webfont.ttf there.
#
# ============================================================ 
# General ESPHome Setup
# ============================================================
# Change the naming below, they will be the names used in Home Assistant

substitutions:     # Modify these to fit your needs
  font_direcotry: D:\Repos\esphome-display\fonts\
  width: 320
  height: 240
  device_name: esp32-cyd-2pt8
  nice_name: ESP32-CYD-2.8in

# ESPHome naming
esphome:
  name: ${device_name}                  # Device hostname
  friendly_name: ${nice_name}           # Friendly name shown in Home Assistant
 
# The ESP32-2432S028 uses a standard ESP32-WROVER, so we use esp32dev
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: zzzzzzzzzzzzsecretzzzzzzzzzzzzzzzzz=

# Set OTA password, enables updates via ESPHome
ota:
  platform: esphome
  password: !secret ota_password

# Setup WiFi credentials, references the wifi ssid and pass in secrets.yaml
wifi:
  ssid: "ssid"
  password: "password"


# Allows captive portal access when in fallback mode
captive_portal:

# ============================================================ 
# ESPHome Display related setup
# ============================================================
# Create a font to use, add and remove glyphs as needed. 
font:
  - file:
      path: /Users/ben/Desktop/esphome/fonts/Arimo-Regular.ttf  # Path to main font file
      type: local
    id: arimo48                                         # ID used to reference this font
    size: 48                                            # Font size
    glyphs:                                             # Characters to include in font. Only 
      - " .,°0123456789:ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+-"                              # add characters you need to reduce memory usage.
  - file:
      path: /Users/ben/Desktop/esphome/fonts/Arimo-Regular.ttf
      type: local
    id: arimo32
    size: 32
    glyphs:
      - " .,°0123456789-+:ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
  - file:                                               # Giving an ID for a larger size of that font.
      path: /Users/ben/Desktop/esphome/fonts/Arimo-Regular.ttf
      type: local
    id: arimo14
    size: 14
    glyphs:
      - "0123456789.:ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz °+-"
  - file:
      path: /Users/ben/Desktop/esphome/fonts/Arimo-Regular.ttf
      type: local
    id: arimo20
    size: 20
    glyphs:
      - " .,°0123456789-+:ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
  - file: /Users/ben/Desktop/esphome/fonts/materialdesignicons-webfont.ttf         # Defining Material Design Icons as a font. This
    id: mdi_icons                                       # will allow us to use them as button icons.
    size: 48                                            # You can get these glyphs from the https://pictogrammers.com/library/mdi/
    glyphs:                                             # where you choose the icon, and then "copy glyph".
      - 󱁑  # mdi-led-strip-variant
      - 󰈐  # mdi-fan
      - 󰏘  # mdi-pallette
      - 󰤝  # mdi-wall-sconce-flat

# Defines the colors we want to use later for the different buttons.
# Per-button customizable colors
color:
  - id: room_bg_color
    hex: "000000"
  - id: default_button_bg_color
    hex: "000000"
  - id: default_button_pressed_bg_color
    hex: "D3D3D3"
  - id: btn_1_color
    hex: FF0000                    # Red
  - id: btn_2_color
    hex: FF7F00                    # Orange
  - id: btn_3_color
    hex: FFFF00                    # Yellow
  - id: btn_4_color
    hex: 00FF00                    # Green
  - id: btn_5_color
    hex: FF1493                    # Pink
  - id: btn_6_color
    hex: "800080"                  # Purple
  - id: btn_7_color
    hex: 0000FF                    # Blue
  - id: btn_8_color
    hex: 00FFFF                    # Aqua
  - id: btn_9_color
    hex: "FFFFFF"                  # White
  - id: btn_10_color
    hex: "FFFFFF"                  # White
  - id: btn_11_color
    hex: "FFFFFF"                  # White
  - id: btn_12_color
    hex: "FFFFFF"                  # White

# ============================================================ 
# Home Assistant related setup
# ============================================================

# ==== Lights ====

# ============================================================ 
# Home Assistant related setup
# ============================================================

# ==== Lights ====
light:
# LCD backlight
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON
# onboard rgb led
  - platform: rgb
    name: "Front LED"
    id: front_led
    restore_mode: ALWAYS_OFF
    red: led_red
    green: led_green
    blue: led_blue

# ==== Sensors for Thermostat ====
sensor:
  - platform: homeassistant
    id: master_bedroom_current_temp
    entity_id: climate.master_bedroom
    attribute: current_temperature
    on_value:
      then:
        - lvgl.arc.update:
            id: temp_arc
            value: !lambda return x;
        - lvgl.label.update:
            id: temp_label
            text: !lambda |-
              char buf[10];
              snprintf(buf, sizeof(buf), "%.1f°C", x);
              return std::string(buf);

  - platform: homeassistant
    id: master_bedroom_target_temp
    entity_id: climate.master_bedroom
    attribute: temperature
    on_value:
      then:
        - lvgl.label.update:
            id: target_temp_label
            text: !lambda |-
              char buf[20];
              snprintf(buf, sizeof(buf), "Target: %.1f°C", x);
              return std::string(buf);

text_sensor:
  - platform: homeassistant
    id: master_bedroom_preset
    entity_id: climate.master_bedroom
    attribute: preset_mode
    on_value:
      then:
        - lvgl.widget.update:
            id: sw_boost
            state:
              checked: !lambda 'return x == "boost";'

# ============================================================ 
# Touchscreen Display related setup
# ============================================================

# SPI bus for TFT display and touch controller
spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    # miso_pin: GPIO12
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

# Set a pin to control the backlight
output:
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm
    frequency: 1000 Hz
    inverted: false
  - platform: ledc
    pin: GPIO04
    id: led_red
    inverted: true
  - platform: ledc
    pin: GPIO17  
    id: led_blue 
    inverted: true
  - platform: ledc
    pin: GPIO16  
    id: led_green 
    inverted: true

# Tracks if recent touch occurred
globals:
  - id: recent_touch
    type: bool
    restore_value: no
    initial_value: "true"

# Defining the touchscreen for later use
touchscreen:
  platform: xpt2046
  id: my_touch 
  spi_id: touch
  cs_pin: 33
  interrupt_pin: 36

  threshold: 400
  calibration:
    x_min: 180
    x_max: 3800
    y_min: 240
    y_max: 3860
  transform:
    swap_xy: true
    mirror_x: false
    mirror_y: false
  on_touch:
    then:
      - light.turn_on: backlight
      - lambda: |-
          id(recent_touch) = true;

# Defining the display type and properties
display:
  - platform: ili9xxx
    color_palette: 8BIT               # Lower memory usage
    model: ILI9341                    # Display driver model
    spi_id: tft
    cs_pin: 
      number: 15
      ignore_strapping_warning: true
    dc_pin:
      number: 2
      ignore_strapping_warning: true
    invert_colors: false
    transform:
      swap_xy: true                   # Orient screen properly
      mirror_y: false                 
      mirror_x: false
    dimensions:
      width: ${width}
      height: ${height}

# Defining the LVGL Layout
lvgl:
  buffer_size: 25%
  theme:
    button:
      bg_color: 0x000000
      bg_opa: COVER
      border_color: 0xFFFFFF
      border_width: 1
      text_color: 0xFFFFFF
      pressed:
        bg_color: 0xC0C0C0
        bg_grad_color: 0xC0C0C0
        bg_opa: COVER
    switch:
      # Simple switch theming
      bg_color: 0x505050
      bg_opa: COVER
      checked:
        bg_color: 0xFFA500 # Orange for boost
  
  pages:
    - id: main_page
      pad_all: 0
      bg_color: 0x000000
      widgets:
        - obj:
            width: ${width}
            height: ${height}
            layout:
              type: flex
              flex_flow: ROW
              flex_align_main: SPACE_BETWEEN
              flex_align_cross: CENTER
            pad_top: 0
            pad_bottom: 0
            pad_right: 0
            pad_left: 10
            bg_color: 0x000000
            border_width: 0
            widgets:
              # Left Side: Thermostat Gauge
              - obj:
                  width: 150
                  height: 200
                  scrollbar_mode: "OFF"
                  pad_all: 0
                  layout:
                    type: flex
                    flex_flow: COLUMN
                    flex_align_main: CENTER
                    flex_align_cross: CENTER
                  bg_opa: TRANSP
                  border_width: 0
                  widgets:
                    - arc:
                        id: temp_arc
                        width: 120
                        height: 120
                        min_value: 10
                        max_value: 30
                        mode: NORMAL
                        arc_width: 10
                        bg_opa: TRANSP
                        flex_grow: 0
                        widgets:
                          - label:
                              id: temp_label
                              text: "--°C"
                              text_font: arimo32
                              text_color: 0xFFFFFF
                              align: CENTER
              
              # Right Side: Controls
              - obj:
                  flex_grow: 1
                  height: 200
                  scrollbar_mode: "OFF"
                  pad_all: 0
                  layout:
                    type: flex
                    flex_flow: COLUMN
                    flex_align_main: CENTER
                    flex_align_cross: CENTER
                  bg_opa: TRANSP
                  border_width: 0
                  widgets:
                    - label:
                        text: "Main Bedroom"
                        text_font: arimo20
                        text_color: 0xFFFFFF
                        align: CENTER
                        pad_bottom: 20px

                    - label:
                        id: target_temp_label
                        text: "Target: --"
                        text_font: arimo14
                        text_color: 0xFFFF00
                        align: CENTER
                        pad_bottom: 20px
                        
                    - label:
                        text: "Heating boost:"
                        text_font: arimo14
                        text_color: 0xFFFFFF
                        align: CENTER
                        pad_bottom: 10px

                    - switch:
                        id: sw_boost
                        height: 40
                        width: 80
                        on_value:
                          then:
                            - if:
                                condition:
                                  lambda: return lv_obj_has_state(id(sw_boost), LV_STATE_CHECKED);
                                then:
                                  - homeassistant.service:
                                      service: hive.boost_heating_on
                                      data:
                                        entity_id: climate.master_bedroom
                                        time_period: "01:30:00"
                                else:
                                  - homeassistant.service:
                                      service: hive.boost_heating_off
                                      data:
                                        entity_id: climate.master_bedroom
